Predicting whether the breast cancer is in Benign stage (starting stage) or in Malignant stage (danger stage) by using Logistic Regression Algorithm which is best for the Binary Classification Technique, as the outcome values can be only of two types either Benign or Malignant. So only two outputs(classes) are possible then it is called Binary classification. 

Logistic Regression is a exponential function where in graph one class of data falls in one side of the curve and other class is on the other side of curve.

STEP:1- Import Libraries

In [ ]:
import numpy as np
import pandas as pd


STEP:2- Input Dataset

In [ ]:
# A)LOADING DATASET:
#Here we use III method to load dataset by directly importing particular dataset according to technique applied(here it is Binary Classification Technique)from
#the sklearn library datasets family as this contains some small datasets that are very easy to access, one of which is the load_breast_cancer dataset which is 
#in form of a function imported from Sklearn datasets which gives binary classification dataset.

#This dataset uses a machine learning algorithm(here Logistic Regression)to classify cancer scans as benign or malignant. It has no Missing attribute or Null 
#values. And all the data types are numerical.
from sklearn.datasets import load_breast_cancer
breast_cancer = load_breast_cancer()
breast_cancer                   #It prints the dataset where 0 represents malignant and 1 represents benign.

{'DESCR': '.. _breast_cancer_dataset:\n\nBreast cancer wisconsin (diagnostic) dataset\n--------------------------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 569\n\n    :Number of Attributes: 30 numeric, predictive attributes and the class\n\n    :Attribute Information:\n        - radius (mean of distances from center to points on the perimeter)\n        - texture (standard deviation of gray-scale values)\n        - perimeter\n        - area\n        - smoothness (local variation in radius lengths)\n        - compactness (perimeter^2 / area - 1.0)\n        - concavity (severity of concave portions of the contour)\n        - concave points (number of concave portions of the contour)\n        - symmetry\n        - fractal dimension ("coastline approximation" - 1)\n\n        The mean, standard error, and "worst" or largest (mean of the three\n        worst/largest values) of these features were computed for each image,\n        resulting in 30 features.

In [ ]:
# B)PREPARING DATASET:
#Separating or defining other var(input columns) in X and categorial var(target column) in Y. Here,by default in given dataset input columns is specified by 'data' 
#which contains all the observed values from tests done on patient and output/target column is specified by 'target'containing 0 and 1 as labels for malignant and
#benign.
X = breast_cancer.data
Y = breast_cancer.target
print(X)
print("#################################################################")
print(Y)


[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
#################################################################
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 

STEP:3- Data Preprocessing 

In [ ]:
#Size of X and Y variable
print(X.shape, Y.shape)     #X has 569 rows/samples and 30 columns/features. And Y has Same rows but has only 1 column.

(569, 30) (569,)


In [ ]:
# Converting part of stored dataset which are all the input columns(other var)stored in 'data'into tabular form i.e. into dataframe by using pandas library,so to
# manipulate the data and do operations on data.The final dataframe containing input columns values is stored in variable'data'.
colm = breast_cancer.feature_names  
# We don't want default columns name of dataset i.e.0,1,..so on, but we want names of columns should be the values of list already given in 'features_names' var
# which is specified in dataset we got from sklearn. 
data = pd.DataFrame(breast_cancer.data, columns=colm)
data.head()


mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [ ]:
#Now we add last new column named as'class'to this dataframe which is categorial/output/target column containing classes 0 or 1 which is stored in form of list 
#in already specified 'target' var in given stored dataset.
data['class'] = breast_cancer.target
data.head()


mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  class  
0          0.4601                  0.11890      0  
1          0.2750                  0.08902      0  
2          0.3613                  0.08758      0  
3          0.6638                  0.17300      0  
4          0.2364                  0.07678      0  

[5 rows x 31 columns]

In [ ]:
#ANALYSING DATASET:

#To see the statistical details of dataset
data.describe()

mean radius  mean texture  mean perimeter    mean area  \
count   569.000000    569.000000      569.000000   569.000000   
mean     14.127292     19.289649       91.969033   654.889104   
std       3.524049      4.301036       24.298981   351.914129   
min       6.981000      9.710000       43.790000   143.500000   
25%      11.700000     16.170000       75.170000   420.300000   
50%      13.370000     18.840000       86.240000   551.100000   
75%      15.780000     21.800000      104.100000   782.700000   
max      28.110000     39.280000      188.500000  2501.000000   

       mean smoothness  mean compactness  mean concavity  mean concave points  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.096360          0.104341        0.088799             0.048919   
std           0.014064          0.052813        0.079720             0.038803   
min           0.052630          0.019380        0.000000             0.000000   
25%           0.086370          0.064920        0.029560             0.020310   
50%           0.095870          0.092630        0.061540             0.033500   
75%           0.105300          0.130400        0.130700             0.074000   
max           0.163400          0.345400        0.426800             0.201200   

       mean symmetry  mean fractal dimension  ...  worst texture  \
count     569.000000              569.000000  ...     569.000000   
mean        0.181162                0.062798  ...      25.677223   
std         0.027414                0.007060  ...       6.146258   
min         0.106000                0.049960  ...      12.020000   
25%         0.161900                0.057700  ...      21.080000   
50%         0.179200                0.061540  ...      25.410000   
75%         0.195700                0.066120  ...      29.720000   
max         0.304000                0.097440  ...      49.540000   

       worst perimeter   worst area  worst smoothness  worst compactness  \
count       569.000000   569.000000        569.000000         569.000000   
mean        107.261213   880.583128          0.132369           0.254265   
std          33.602542   569.356993          0.022832           0.157336   
min          50.410000   185.200000          0.071170           0.027290   
25%          84.110000   515.300000          0.116600           0.147200   
50%          97.660000   686.500000          0.131300           0.211900   
75%         125.400000  1084.000000          0.146000           0.339100   
max         251.200000  4254.000000          0.222600           1.058000   

       worst concavity  worst concave points  worst symmetry  \
count       569.000000            569.000000      569.000000   
mean          0.272188              0.114606        0.290076   
std           0.208624              0.065732        0.061867   
min           0.000000              0.000000        0.156500   
25%           0.114500              0.064930        0.250400   
50%           0.226700              0.099930        0.282200   
75%           0.382900              0.161400        0.317900   
max           1.252000              0.291000        0.663800   

       worst fractal dimension       class  
count               569.000000  569.000000  
mean                  0.083946    0.627417  
std                   0.018061    0.483918  
min                   0.055040    0.000000  
25%                   0.071460    0.000000  
50%                   0.080040    1.000000  
75%                   0.092080    1.000000  
max                   0.207500    1.000000  

[8 rows x 31 columns]

In [ ]:
#To find the number of cases or rows containing malignant(rep by 0) and no of rows containing benign(rep by 1) class. So value_counts()function gives the number i.e.
#count of different values in particular column.
print(data['class'].value_counts())

1    357
0    212
Name: class, dtype: int64


In [ ]:
#To print what 0 and 1 represents which is already specified in var'target_names' of given stored dataset in breast_cancer.
print(breast_cancer.target_names)
# 0 - Malignant
# 1 - Benign

['malignant' 'benign']


In [ ]:
#To find mean value for each column of all benign(1) and malignant(0) class.
data.groupby('class').mean()   
#Returns a groupby object that contains information about the each groups,here 0 & 1. And then find mean of each grouped values for dataframe.

#We will see the mean values of class 0 columns are more than mean values of class 1, i.e.the mean values are high in case of malignant and they are low for benign.
 

mean radius  mean texture  mean perimeter   mean area  mean smoothness  \
class                                                                           
0        17.462830     21.604906      115.365377  978.376415         0.102898   
1        12.146524     17.914762       78.075406  462.790196         0.092478   

       mean compactness  mean concavity  mean concave points  mean symmetry  \
class                                                                         
0              0.145188        0.160775             0.087990       0.192909   
1              0.080085        0.046058             0.025717       0.174186   

       mean fractal dimension  ...  worst radius  worst texture  \
class                          ...                                
0                    0.062680  ...     21.134811      29.318208   
1                    0.062867  ...     13.379801      23.515070   

       worst perimeter   worst area  worst smoothness  worst compactness  \
class                                                                      
0           141.370330  1422.286321          0.144845           0.374824   
1            87.005938   558.899440          0.124959           0.182673   

       worst concavity  worst concave points  worst symmetry  \
class                                                          
0             0.450606              0.182237        0.323468   
1             0.166238              0.074444        0.270246   

       worst fractal dimension  
class                           
0                     0.091530  
1                     0.079442  

[2 rows x 30 columns]

In [ ]:
#SPLITTING DATASET INTO TRAINING & TESTING DATASET:
#Split arrays or matrices(i.e.dataframe) into random train and test subsets.X_train is training subset & X_test is testing subset and Y_train is labels for training
#data and Y_test is labels for testing data.
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y)

In [ ]:
#No of samples/rows of training and testing subsets i.e. how many samples it has randomly splitted as train and test data.
print(Y.shape, Y_train.shape, Y_test.shape)

(569,) (426,) (143,)


In [ ]:
#So we don't need this many rows(i.e.143 samples)in testing subset, and need only 10% of total data as testing data so we specify i.e.10% of test data.The parameter
#used to specify this is keyword test_size. 
X_train, X_test, Y_train, Y_test= train_test_split(X, Y, test_size=0.1)      # 0.1 represents 10% of test data size.
#Now again check the size of test data
print(Y.shape, Y_train.shape, Y_test.shape)
#So now we have only 57 samples in test subset.

(569,) (512,) (57,)


In [ ]:
#Now we find mean of train and test data also as mean should be same for original, training and testing data.As this shows that data splitted is similar to original 
#data.
print(Y.mean(), Y_train.mean(), Y_test.mean())


0.6274165202108963 0.63671875 0.543859649122807


In [ ]:
#We see that since malignant and benign states are not equally distributed in original data so there is difference in mean of Y_test.So we need these three means
#to be approx equal by passing parameter as keyword 'stratify', which makes data to be split in a stratified fashion, using this as the class labels.
#We stratify based on Y i.e.based on labels 0 & 1, equal distribution should be there for 0 & 1. This means it splits samples such that train and test labels both
#have distribution with same percentage of 0 and 1 classes according to size of train and test subsets as that of original dataset which ensure to give same mean.
X_train, X_test, Y_train, Y_test= train_test_split(X, Y, test_size=0.1, stratify=Y)
#Now again see mean of values for Y.
print(Y.mean(), Y_train.mean(), Y_test.mean())
#Thus we see the mean of all three are almost same or similar.


0.6274165202108963 0.626953125 0.631578947368421


In [ ]:
#Now if we want our dataset to be splitted in same random samples everytime on execution we pass parameter as keyword 'random_state'which has some value. This is 
#useful to reproduce or replicate the same(or exact) output again and again.
X_train, X_test, Y_train, Y_test= train_test_split(X, Y, test_size=0.1, stratify=Y, random_state=1)


In [ ]:
# test_size --> to specify the percentage of test data needed.
# stratify --> for correct distribution of data as of the original data.
# random_state --> Each integer value of random_state splits the data differently & gives fixed specific split of data.

In [ ]:
#The mean value of X_train & X_test is not same as they contain 30 features/columns & it find mean for each column.So we only needed the Y value to be distributed
#equally. There will be some difference in means of X which is fine.
print(X.mean(), X_train.mean(), X_test.mean())

61.890712339519624 61.31637960106119 67.04963097269005


In [ ]:
print(X_train)

[[1.490e+01 2.253e+01 1.021e+02 ... 2.475e-01 2.866e-01 1.155e-01]
 [1.205e+01 1.463e+01 7.804e+01 ... 6.548e-02 2.747e-01 8.301e-02]
 [1.311e+01 1.556e+01 8.721e+01 ... 1.986e-01 3.147e-01 1.405e-01]
 ...
 [1.258e+01 1.840e+01 7.983e+01 ... 8.772e-03 2.505e-01 6.431e-02]
 [1.349e+01 2.230e+01 8.691e+01 ... 1.282e-01 2.871e-01 6.917e-02]
 [1.919e+01 1.594e+01 1.263e+02 ... 1.777e-01 2.443e-01 6.251e-02]]


STEP:4 - Training the Model

In [ ]:
#importing logistic regression model from sklearn.
from sklearn.linear_model import LogisticRegression
#This model is stored in form of class in family of sklearn. So we create an object to access the model class members.
classifier = LogisticRegression()
#Now we have to fit the training dataset to this classifier which is our Logistic regression Model i.e.train this model with training dataset. So basically this is 
#done by calling member function fit() of class by object classifier.
# Training the model on training data.
classifier.fit(X_train, Y_train)       #Where X_train is training dataset and Y_train is training data labels i.e.classes of X_train.                                                                                                                                                                                                                                                                                                                                                   object to access model class members.


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

STEP:5 - Testing the Model (with test data which it has not seen yet)

In [ ]:
#Predict class labels(i.e.0 or 1) for samples(testing data) in X. The X_test is the data matrix for which we want to get the predictions which we already know,
#as we only doing this to check how model predicts the classes for data.
classifier.predict(X_test)

array([1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1])

STEP:6- Evaluation:- Finding the Efficiency of Model



In [ ]:
#To find efficiency of model which uses classification technique, we import accuracy_score model which is stored in form of function.
from sklearn.metrics import accuracy_score


In [ ]:
#Now, evaluating on how model works on training data: 
Y_train_predict = classifier.predict(X_train)              #First it predicts the labels of X_train.
#It compares actual label values of Y_train with the predicted label values by model in Y_train_predict and gives the percentage of how much data model can predicts 
#correctly.
train_efficiency = accuracy_score(Y_train, Y_train_predict) 
print("Accuracy on training data : ",train_efficiency)
#It gives high accuracy as model already has seen the training data as it was trained with this data only but haven't seen the test data till now. So we need to 
#check accuracy on test data also.


Accuracy on training data :  0.951171875


In [ ]:
#Similarly, evaluating on how well model works for testing data:
Y_test_predict = classifier.predict(X_test)                #First it predicts the labels of X_test.
#It compares correct or actual values with the values the model has predicted.
test_efficiency = accuracy_score(Y_test, Y_test_predict)
print("Accuracy on testing data : ",test_efficiency)

#We can also find accuracy with other models for this dataset only to check which model gives good Acccuracy Score.

Accuracy on testing data :  0.9298245614035088


STEP:7- Actual Working of Model as Predictive System

In [ ]:
#Detecting whether the patient has breast cancer in Benign or Malignant stage by giving new input data which are the observations we got from the tests performed
#on patient i.e.totally new or unknown data is given to model on the basis of  which it predict class(benign or malignant) to which patient belong.
# So we give all the features value here as input data.
input_data = (17.99,10.38,122.8,1001,0.1184,0.2776,0.3001,0.1471,0.2419,0.07871,1.095,0.9053,8.589,153.4,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.38,
              17.33,184.6,2019,0.1622,0.6656,0.7119,0.2654,0.4601,0.1189)
#change or convert the input data which is in tuple to numpy array to make prediction, by using the function asarray().  
input_array = np.asarray(input_data)
print(input_array)

#Now we need to reshape the array i.e.change size of array as we are predicting class for single instance(for one row)only.
input_reshaped = input_array.reshape(1,-1)
print(input_reshaped)


[1.799e+01 1.038e+01 1.228e+02 1.001e+03 1.184e-01 2.776e-01 3.001e-01
 1.471e-01 2.419e-01 7.871e-02 1.095e+00 9.053e-01 8.589e+00 1.534e+02
 6.399e-03 4.904e-02 5.373e-02 1.587e-02 3.003e-02 6.193e-03 2.538e+01
 1.733e+01 1.846e+02 2.019e+03 1.622e-01 6.656e-01 7.119e-01 2.654e-01
 4.601e-01 1.189e-01]
[[1.799e+01 1.038e+01 1.228e+02 1.001e+03 1.184e-01 2.776e-01 3.001e-01
  1.471e-01 2.419e-01 7.871e-02 1.095e+00 9.053e-01 8.589e+00 1.534e+02
  6.399e-03 4.904e-02 5.373e-02 1.587e-02 3.003e-02 6.193e-03 2.538e+01
  1.733e+01 1.846e+02 2.019e+03 1.622e-01 6.656e-01 7.119e-01 2.654e-01
  4.601e-01 1.189e-01]]


In [ ]:
#Predicting the output for this set of input values.
#Since our Logistic Regression model class has object named classifier which is used to access the functions of class

prediction = classifier.predict(input_reshaped)
#On the basis of input data given to model it predict stage of cancer which is represented by either 0 or 1.
print(prediction)
#It returns the list having one element either [0] if Malignant or [1] if Benign.

if prediction[0]==0:            #It access the first & only element of list at index 0 stored in prediction variable and check if it is equal to 0. 
    print("The Breast Cancer is Malignant")
else:
    print("The Breast Cancer is Benign")    


[0]
The Breast Cancer is Malignant
